{% set version = "0.2.3" %}

package:
  name: libdecor
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/libdecor/libdecor/-/archive/{{ version }}/libdecor-{{ version }}.tar.bz2
  sha256: 704138616a96eafbe68bbd5e55df2c8adb21ae5ec165ba56b6ea1f99869167d5

build:
  skip: true  # [not linux]
  number: 0
  ignore_run_exports_from:
    # Needed to detect glib correctly
    - liblzma-devel

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - meson
    - ninja
    - pkg-config
  host:
    - wayland
    - wayland-protocols
    - cairo
    - pango
    - dbus
    - gtk3
    - glib
    - expat
    # needed to find glib correctly
    - liblzma-devel
    - zlib

test:
  commands:
    - test -f "${PREFIX}/lib/libdecor-0.so"
    - test -f "${PREFIX}/include/libdecor-0/libdecor.h"

about:
  home: https://gitlab.freedesktop.org/libdecor/libdecor
  summary: A client-side decorations library for Wayland client
  description: |
    libdecor is a library that can help Wayland clients draw window decorations
    for them. It aims to provide multiple backends that implements the
    decoration drawing.

  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
